/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package myTech;
import java.awt.Color;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Admin extends javax.swing.JFrame {
    Koneksi conek = new Koneksi();
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        datatable();
        IDADMIN.setBackground(new Color (0,0,0,0));
        IDADMIN.setBorder(null);
        NAMAADMIN.setBackground(new Color (0,0,0,0));
        NAMAADMIN.setBorder(null);
        USERNAME.setBackground(new Color (0,0,0,0));
        USERNAME.setBorder(null);
        PASSWORD.setBackground(new Color (0,0,0,0));
        PASSWORD.setBorder(null);
        NOTELPON.setBackground(new Color (0,0,0,0));
        NOTELPON.setBorder(null);
        TTL.setBackground(new Color (0,0,0,0));
        TTL.setBorder(null);
        ALAMAT.setBackground(new Color (0,0,0,0));
        ALAMAT.setBorder(null);
    }
    
    void datatable() {
        try {
            Statement statement=conek.GetConnection().createStatement();
            ResultSet res = (ResultSet) statement.executeQuery("select * from admin");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("id admin");
            tbl.addColumn("nama");
            tbl.addColumn("username");
            tbl.addColumn("tanggal lahir");
            tbl.addColumn("no telp");
            tbl.addColumn("alamat");
            tbl.addColumn("created at");
            table.setModel(tbl);
            while (res.next()) {
                tbl.addRow(new Object[]{
                        res.getString("id_admin"),
                        res.getString("nama"),
                        res.getString("username"),
                        res.getString("tanggal_lahir"),
                        res.getString("no_telp"),
                        res.getString("alamat"),
                        res.getString("created_at"),
                    });
                table.setModel(tbl);
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah "+e);
        }
    }
    
    void reset () {
        IDADMIN.setText("");
        NAMAADMIN.setText("");
        USERNAME.setText("");
        PASSWORD.setText("");
        NOTELPON.setText("");
        TTL.setText("");
        ALAMAT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ALAMAT = new javax.swing.JTextField();
        IDADMIN = new javax.swing.JTextField();
        NAMAADMIN = new javax.swing.JTextField();
        USERNAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JTextField();
        NOTELPON = new javax.swing.JTextField();
        TTL = new com.github.lgooddatepicker.components.DatePicker();
        csupplier = new javax.swing.JLabel();
        ckategori = new javax.swing.JLabel();
        cbarang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("EDIT");
        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 110, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id admin", "nama admin", "username", "email", "no telephone", "tanggal lahir", "alamat", "create at"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 620, 360));
        getContentPane().add(ALAMAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 240, -1));

        IDADMIN.setBorder(null);
        IDADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDADMINActionPerformed(evt);
            }
        });
        getContentPane().add(IDADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 156, 240, 30));
        getContentPane().add(NAMAADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 240, -1));
        getContentPane().add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 240, -1));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 110, 30));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 110, 30));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 110, 30));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 110, 30));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 600, 110, 30));
        getContentPane().add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 240, -1));
        getContentPane().add(NOTELPON, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 240, -1));
        getContentPane().add(TTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 250, -1));

        csupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        csupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csupplierMouseClicked(evt);
            }
        });
        getContentPane().add(csupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 66, 110, 20));

        ckategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ckategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckategoriMouseClicked(evt);
            }
        });
        getContentPane().add(ckategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 110, 30));

        cbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbarangMouseClicked(evt);
            }
        });
        getContentPane().add(cbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 66, 130, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/Admin Fiks.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try {
            Statement statement = conek.GetConnection().createStatement();
            String query = "UPDATE admin SET "
                    +"nama = '" + NAMAADMIN.getText()+ "',"
                    +"username = '" + USERNAME.getText() + "',"
                    + "no_telp = '" + NOTELPON.getText() + "',"
                    + "tanggal_lahir = '" + TTL.getDate() + "',"
                    + "alamat = '" + ALAMAT.getText() + "' "
                    + "WHERE id_admin = '"+ IDADMIN.getText() +"'";
                    
            statement.executeUpdate(query);
            datatable();
            reset();
            
        }catch (Exception e){
           JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void IDADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDADMINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDADMINActionPerformed

    private void cbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbarangMouseClicked
        // TODO add your handling code here:
        Barang a = new Barang();
        a.setVisible(true);
        dispose();
        a.setExtendedState(Barang.MAXIMIZED_BOTH);
    }//GEN-LAST:event_cbarangMouseClicked

    private void csupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csupplierMouseClicked
        // TODO add your handling code here:
        Supplier a = new Supplier();
        a.setVisible(true);
        dispose();
        a.setExtendedState(Supplier.MAXIMIZED_BOTH);
    }//GEN-LAST:event_csupplierMouseClicked

    private void ckategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckategoriMouseClicked
        // TODO add your handling code here:
        Kategori a = new Kategori();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_ckategoriMouseClicked

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        int row = table.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        IDADMIN.setText(tableModel.getValueAt(row, 0).toString());
        NAMAADMIN.setText(tableModel.getValueAt(row, 1).toString());
        USERNAME.setText(tableModel.getValueAt(row, 2).toString());
        LocalDate date = LocalDate.parse(tableModel.getValueAt(row, 3).toString());
        TTL.setDate(date);
        NOTELPON.setText(tableModel.getValueAt(row, 4).toString());
        ALAMAT.setText(tableModel.getValueAt(row, 5).toString());
    }//GEN-LAST:event_tableMouseReleased

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        String nama = NAMAADMIN.getText();
        String user = USERNAME.getText();
        String password = PASSWORD.getText();
        String notelf = NOTELPON.getText();
        String ttl = TTL.getDate().toString();
        String alamat = ALAMAT.getText();
        LocalDate currentDate = LocalDate.now();
        Koneksi cn = new Koneksi();
        try {
            Statement statement = conek.GetConnection().createStatement();
            statement.executeUpdate("insert into admin(nama,tanggal_lahir,no_telp,alamat,password,username,created_at) VALUES ('"+nama+"','"+ttl+"','"+notelf+"','"+alamat+"','"+password+"','"+user+"', '"+currentDate+"')");
            datatable();
            reset();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        try {
            Statement statement=conek.GetConnection().createStatement();
            ResultSet res = (ResultSet) statement.executeQuery("select * from admin where id_admin = '"+IDADMIN.getText()+"'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("id admin");
            tbl.addColumn("nama");
            tbl.addColumn("username");
            tbl.addColumn("tanggal lahir");
            tbl.addColumn("no telp");
            tbl.addColumn("alamat");
            tbl.addColumn("created at");
            table.setModel(tbl);
            while (res.next()) {
                tbl.addRow(new Object[]{
                        res.getString("id_admin"),
                        res.getString("nama"),
                        res.getString("username"),
                        res.getString("tanggal_lahir"),
                        res.getString("no_telp"),
                        res.getString("alamat"),
                        res.getString("created_at"),
                    });
                table.setModel(tbl);
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah "+e);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        String idadmin = IDADMIN.getText();
        try {
            Statement statement=conek.GetConnection().createStatement();
            statement.executeUpdate("DELETE from admin where id_admin=('" + IDADMIN.getText() + "');" );          
            JOptionPane.showMessageDialog(null, "data berhasil di HAPUS");
            datatable();
            reset();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal di HAPUS" + e);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Home home = new Home();
        home.setVisible(true);
        home.setExtendedState(Home.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jLabel6MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (admin.UserAdmin.getName() == null) {
                    Login login = new Login();
                    login.setVisible(true);
                    login.setExtendedState(Login.MAXIMIZED_BOTH);
                } else {
                    new Admin().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ALAMAT;
    private javax.swing.JTextField IDADMIN;
    private javax.swing.JTextField NAMAADMIN;
    private javax.swing.JTextField NOTELPON;
    private javax.swing.JTextField PASSWORD;
    private com.github.lgooddatepicker.components.DatePicker TTL;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JLabel cbarang;
    private javax.swing.JLabel ckategori;
    private javax.swing.JLabel csupplier;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
