/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package myTech;

import java.awt.Color;
import java.sql.*;
import java.awt.HeadlessException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Barang extends javax.swing.JInternalFrame {
    Koneksi koneksi = new Koneksi();
    String sql;
    private Object tabel;
    private String title;

    public Barang() {
        initComponents();
        datatable("");
        setKategori();
        txtidbarang.setBackground(new Color (0,0,0,0));
        txtidbarang.setBorder(null);
        txtnamabarang.setBackground(new Color (0,0,0,0));
        txtnamabarang.setBorder(null);
        txtkategori.setBackground(new Color (0,0,0,0));
        txtkategori.setBorder(null);
        txthargajual.setBackground(new Color (0,0,0,0));
        txthargajual.setBorder(null);
        txthargabeli.setBackground(new Color (0,0,0,0));
        txthargabeli.setBorder(null);
        txtstok.setBackground(new Color (0,0,0,0));
        txtstok.setBorder(null);
        txtdeskripsi.setBackground(new Color (0,0,0,0));
        txtdeskripsi.setBorder(null);
        txtsatuan.setBackground(new Color (0,0,0,0));
        txtsatuan.setBorder(null);
        btambah.setBackground(new Color (0,0,0,0));
        btambah.setBorder(null);
        bcari.setBackground(new Color (0,0,0,0));
        bcari.setBorder(null);
        bsimpan.setBackground(new Color (0,0,0,0));
        bsimpan.setBorder(null);
        bhapus.setBackground(new Color (0,0,0,0));
        bhapus.setBorder(null);
        breset.setBackground(new Color (0,0,0,0));
        breset.setBorder(null);
        bkeluar.setBackground(new Color (0,0,0,0));
        bkeluar.setBorder(null);
    }
    
    void setKategori () {
        try {
            Statement stat = koneksi.GetConnection().createStatement();
            ResultSet res = stat.executeQuery("SELECT * FROM kategori");
            while(res.next()) txtkategori.addItem(res.getString("nama"));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "error "+e);
        }
    }
    
    private void datatable(String select_from_barang) {
        
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("Id Barang");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Kategori");
        tbl.addColumn("Harga Jual");
        tbl.addColumn("Harga Beli");
        tbl.addColumn("Stok");
        tbl.addColumn("Deskripsi");
        tbl.addColumn("Satuan");
        tbl.addColumn("Created At");
        tablebarang.setModel(tbl);
        try{
            Statement statement = koneksi.GetConnection().createStatement();
            if (select_from_barang.equals("")) {
                sql = "SELECT barang.*, kategori.nama as kategori FROM `barang` inner join kategori on barang.id_kategori = kategori.id_kategori";
            } else {
                sql = select_from_barang;
            }
            ResultSet res = statement.executeQuery
                (sql);
            while(res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("id_barang"),
                    res.getString("nama"),
                    res.getString("kategori"),
                    res.getString("harga_jual"),
                    res.getString("harga_beli"),
                    res.getString("jumlah_stok"),
                    res.getString("deskripsi"),
                    res.getString("satuan"),
                    res.getString("created_at"),
                });
                tablebarang.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane,"salah" +e);
        }
    }
    void reset() {
        txtidbarang.setText("");
        txtnamabarang.setText("");
        txthargajual.setText("");
        txthargabeli.setText("");
        txtkategori.setSelectedIndex(0);
        txtstok.setText("");
        txtdeskripsi.setText("");
        txtsatuan.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidbarang = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        txthargajual = new javax.swing.JTextField();
        txthargabeli = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        btambah = new javax.swing.JButton();
        bcari = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablebarang = new javax.swing.JTable();
        txtdeskripsi = new javax.swing.JTextField();
        txtsatuan = new javax.swing.JTextField();
        breset = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        cadmin = new javax.swing.JLabel();
        csupplier = new javax.swing.JLabel();
        txtkategori = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ckategori = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtidbarang.setBorder(null);
        txtidbarang.setForeground(new java.awt.Color(255, 255, 255));
        txtidbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidbarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtidbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 260, 20));

        txtnamabarang.setBorder(null);
        getContentPane().add(txtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 260, 20));

        txthargajual.setBorder(null);
        getContentPane().add(txthargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 260, 20));

        txthargabeli.setBorder(null);
        getContentPane().add(txthargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 260, 20));

        txtstok.setBorder(null);
        getContentPane().add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 260, 20));

        btambah.setText("Tambah");
        btambah.setBorder(null);
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        getContentPane().add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 110, 30));

        bcari.setText("Cari");
        bcari.setBorder(null);
        bcari.setForeground(new java.awt.Color(255, 255, 255));
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 110, 30));

        bhapus.setText("Hapus");
        bhapus.setBorder(null);
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 110, 30));

        bkeluar.setText("Keluar");
        bkeluar.setBorder(null);
        bkeluar.setForeground(new java.awt.Color(255, 255, 255));
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 630, 120, 30));

        tablebarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Barang", "Nama Barang", "Kategori", "Harga Jual", "Harga Beli", "Jumlah Stok", "Deskripsi", "Satuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablebarang.setGridColor(new java.awt.Color(255, 255, 255));
        tablebarang.setSelectionBackground(new java.awt.Color(102, 0, 204));
        tablebarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablebarangMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tablebarang);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 630, 380));

        txtdeskripsi.setBorder(null);
        txtdeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        txtdeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeskripsiActionPerformed(evt);
            }
        });
        getContentPane().add(txtdeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 260, 20));

        txtsatuan.setBorder(null);
        txtsatuan.setForeground(new java.awt.Color(255, 255, 255));
        txtsatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsatuanActionPerformed(evt);
            }
        });
        getContentPane().add(txtsatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 260, 20));

        breset.setText("Reset");
        breset.setBorder(null);
        breset.setForeground(new java.awt.Color(255, 255, 255));
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        getContentPane().add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 570, 120, 30));

        bsimpan.setText("Simpan");
        bsimpan.setBorder(null);
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 660, 110, 30));

        cadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadminMouseClicked(evt);
            }
        });
        getContentPane().add(cadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 110, 20));

        csupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        csupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csupplierMouseClicked(evt);
            }
        });
        getContentPane().add(csupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 110, 20));

        txtkategori.setBorder(null);
        txtkategori.setForeground(new java.awt.Color(255, 255, 255));
        txtkategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtkategoriItemStateChanged(evt);
            }
        });
        txtkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkategoriActionPerformed(evt);
            }
        });
        getContentPane().add(txtkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 260, 20));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 110, 20));

        ckategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/Barang Fiks.png"))); // NOI18N
        getContentPane().add(ckategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        String idbarang = txtidbarang.getText();
        String namabarang = txtnamabarang.getText();
        int kategori = txtkategori.getSelectedIndex()+1;
        String hargajual = txthargajual.getText();
        String hargabeli = txthargabeli.getText();
        String stok = txtstok.getText();
        String deskripsi = txtdeskripsi.getText();
        String satuan = txtsatuan.getText();
        LocalDate currentDate = LocalDate.now();
        try{
            Statement statement = koneksi.GetConnection().createStatement();
            statement.executeUpdate("insert into "
                    + "barang(nama, id_kategori, harga_jual, harga_beli, jumlah_stok, deskripsi, satuan, created_at) "
                    + "VALUES ('" + namabarang + "', '"+kategori+"', '" + hargajual + "', '" 
                    + hargabeli + "', '" + stok +"', '" + deskripsi + "', '"+ satuan +"', '"+ currentDate +"')"); 
            datatable("");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btambahActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        String idbarang = txtidbarang.getText();
        String namabarang = txtnamabarang.getText();
        
        try{
                Statement statement = koneksi.GetConnection().createStatement();
                ResultSet res = statement.executeQuery
                    ("SELECT * from barang where id_barang LIKE '%" + idbarang + "%' AND nama LIKE '%"+namabarang+"%'");
                DefaultTableModel tbl = new DefaultTableModel();
                tbl.addColumn("Id Barang");
                tbl.addColumn("Nama Barang");
                tbl.addColumn("Kategori");
                tbl.addColumn("Harga Jual");
                tbl.addColumn("Harga Beli");
                tbl.addColumn("Stok");
                tbl.addColumn("Deskripsi");
                tbl.addColumn("Satuan");
                tablebarang.setModel(tbl);

                while(res.next()){
                    tbl.addRow(new Object[]{
                        res.getString("id_barang"),
                        res.getString("nama"),
                        res.getString("id_kategori"),
                        res.getString("harga_jual"),
                        res.getString("harga_beli"),
                        res.getString("jumlah_stok"),
                        res.getString("deskripsi"),
                        res.getString("satuan"),
                    });
                    tablebarang.setModel(tbl);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "salah" +e);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        String idbarang = txtidbarang.getText();
        String namabarang = txtnamabarang.getText();
        String hargajual = txthargajual.getText();
        String hargabeli = txthargabeli.getText();
        int kategori = txtkategori.getSelectedIndex()+1;
        String deskripsi = txtstok.getText();
        try{
            Statement statement = koneksi.GetConnection().createStatement();
            statement.executeUpdate
                ("DELETE FROM barang WHERE id_barang = '" + idbarang + "'");
            JOptionPane.showMessageDialog
                (null, "data berhasil dihapus");
            datatable("");
            reset();
        } catch (Exception t){
            JOptionPane.showMessageDialog
            (null, "Data gagal dihapus" +t);
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
            dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    private void tablebarangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebarangMouseReleased
        // TODO add your handling code here:
        int row = tablebarang.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) tablebarang.getModel();
        txtidbarang.setText(table.getValueAt(row, 0).toString());
        txtnamabarang.setText(table.getValueAt(row, 1).toString());
        txtkategori.setSelectedItem(table.getValueAt(row, 2).toString());
        txthargajual.setText(table.getValueAt(row, 3).toString());
        txthargabeli.setText(table.getValueAt(row, 4).toString());
        txtstok.setText(table.getValueAt(row, 5).toString());
        txtdeskripsi.setText(table.getValueAt(row, 6).toString());
        txtsatuan.setText(table.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tablebarangMouseReleased

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        
        String idbarang1 = txtidbarang.getText();
        String namabarang1 = txtnamabarang.getText();
        String hargajual = txthargajual.getText();
        String hargabeli = txthargabeli.getText();
        int kategori = txtkategori.getSelectedIndex()+1;
        String stok = txtstok.getText();
        String satuan = txtsatuan.getText();
        String deskripsi = txtdeskripsi.getText();

        try{
            Statement statement = koneksi.GetConnection().createStatement();
            String query = "UPDATE barang SET " 
                + "nama = '" +namabarang1+ "',"
                + "harga_jual = '" +hargajual+ "',"
                + "harga_beli = '" +hargabeli+ "',"
                + "id_kategori = '" +kategori+ "',"
                + "jumlah_stok = '" +stok+ "',"
                + "satuan = '" +satuan+ "',"
                + "deskripsi = '" +deskripsi+ "'"
                + "WHERE id_barang = '" +idbarang1+ "'";
            statement.executeUpdate(query);
            datatable("");
            JOptionPane.showMessageDialog(null, "Perubahan berhasil disimpan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "gagal "+e);
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void txtkategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtkategoriItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkategoriItemStateChanged

    private void txtsatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsatuanActionPerformed

    private void txtkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkategoriActionPerformed

    private void txtidbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidbarangActionPerformed

    private void txtdeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeskripsiActionPerformed

    private void cadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadminMouseClicked
        // TODO add your handling code here:
        Admin a = new Admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_cadminMouseClicked

    private void csupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csupplierMouseClicked
        // TODO add your handling code here:
        Supplier a = new Supplier();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_csupplierMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Kategori a = new Kategori();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JLabel cadmin;
    private javax.swing.JLabel ckategori;
    private javax.swing.JLabel csupplier;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablebarang;
    private javax.swing.JTextField txtdeskripsi;
    private javax.swing.JTextField txthargabeli;
    private javax.swing.JTextField txthargajual;
    private javax.swing.JTextField txtidbarang;
    private javax.swing.JComboBox<String> txtkategori;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtsatuan;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables


}
