/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package myTech;

import java.awt.Color;
import java.sql.*;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Beli extends javax.swing.JInternalFrame {
    Koneksi koneksi = new Koneksi();
    String sql;
    /**
     * Creates new form Beli
     */
    public Beli() {
        initComponents();
        datatable("");
        setSupplier();
        autosum(); 
        txtidbarang.setBackground(new Color (0,0,0,0));
        txtidbarang.setBorder(null);
        txtnamabarang.setBackground(new Color (0,0,0,0));
        txtnamabarang.setBorder(null);
        txthargasatuan.setBackground(new Color (0,0,0,0));
        txthargasatuan.setBorder(null);
        txtjumlahbarang.setBackground(new Color (0,0,0,0));
        txtjumlahbarang.setBorder(null);
        txttotal.setBackground(new Color (0,0,0,0));
        txttotal.setBorder(null);
        txtuang.setBackground(new Color (0,0,0,0));
        txtuang.setBorder(null);
        txtkembalian.setBackground(new Color (0,0,0,0));
        txtkembalian.setBorder(null);
        btambah.setBackground(new Color (0,0,0,0));
        btambah.setBorder(null);
        Csupplier.setBackground(new Color (0,0,0,0));
        Csupplier.setBorder(null);
        bproses.setBackground(new Color (0,0,0,0));
        bproses.setBorder(null);
        bhapus.setBackground(new Color (0,0,0,0));
        bhapus.setBorder(null);
    }
    
    private void setSupplier () {
        try {
            Statement stat = koneksi.GetConnection().createStatement();
            ResultSet res = stat.executeQuery("SELECT * FROM supplier");
            while(res.next()) Csupplier.addItem(res.getString("id_supplier").concat(". "+res.getString("nama")));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "error "+e);
        }
    }
 
    private void autosum (){
        int total = 0;
        
        for (int i = 0; i <tablebarangfiks.getRowCount(); i++){
            int amount = Integer.parseInt((String)tablebarangfiks.getValueAt(i,4));
            total += amount;
        }
        txttotal.setText(""+total);
    }   
    
    private void datatable(String select_from_beli) {
        
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("Id Barang");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Kategori");
        tbl.addColumn("Harga Jual");
        tbl.addColumn("Harga Beli");
        tbl.addColumn("Stok");
        tbl.addColumn("Deskripsi");
        tbl.addColumn("Satuan");
        tablebarangsementara.setModel(tbl);
        try{
            Statement statement = koneksi.GetConnection().createStatement();
            if (select_from_beli.equals("")) {
                sql = "SELECT barang.*, kategori.nama as kategori FROM `barang` inner join kategori on barang.id_kategori = kategori.id_kategori";
            } else {
                sql = select_from_beli;
            }
            ResultSet res = statement.executeQuery(sql);
            while(res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("id_barang"),
                    res.getString("nama"),
                    res.getString("kategori"),
                    res.getString("harga_jual"),
                    res.getString("harga_beli"),
                    res.getString("jumlah_stok"),
                    res.getString("deskripsi"),
                    res.getString("satuan"),
                });
                tablebarangsementara.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane,"salah" +e);
        }
    }    
    
    void reset() {
        DefaultTableModel tableModel = (DefaultTableModel) tablebarangfiks.getModel();
        tableModel.setRowCount(0);
        txtuang.setText("");
        txtkembalian.setText("");
        txttotal.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtuang = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        txtjumlahbarang = new javax.swing.JTextField();
        btambah = new javax.swing.JButton();
        bproses = new javax.swing.JButton();
        Csupplier = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablebarangsementara = new javax.swing.JTable();
        txthargasatuan = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablebarangfiks = new javax.swing.JTable();
        bhapus = new javax.swing.JButton();
        tglpembelian = new com.github.lgooddatepicker.components.DatePicker();
        jLabel18 = new javax.swing.JLabel();
        txtidbarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PEMBELIAN");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, -20, -1, 17));

        txttotal.setBorder(null);
        txttotal.setForeground(new java.awt.Color(255, 255, 255));
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 340, 30));

        txtuang.setBorder(null);
        txtuang.setForeground(new java.awt.Color(255, 255, 255));
        txtuang.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtuangCaretUpdate(evt);
            }
        });
        txtuang.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtuangInputMethodTextChanged(evt);
            }
        });
        txtuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuangActionPerformed(evt);
            }
        });
        txtuang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuangKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuangKeyTyped(evt);
            }
        });
        getContentPane().add(txtuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 340, 30));

        txtnamabarang.setBorder(null);
        txtnamabarang.setForeground(new java.awt.Color(255, 255, 255));
        txtnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 100, 30));

        txtkembalian.setBorder(null);
        txtkembalian.setForeground(new java.awt.Color(255, 255, 255));
        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });
        txtkembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkembalianKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkembalianKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkembalianKeyTyped(evt);
            }
        });
        getContentPane().add(txtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 340, 30));

        txtjumlahbarang.setBorder(null);
        txtjumlahbarang.setForeground(new java.awt.Color(255, 255, 255));
        txtjumlahbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahbarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtjumlahbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 105, 30));

        btambah.setBorder(null);
        btambah.setForeground(new java.awt.Color(255, 255, 255));
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        getContentPane().add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 40, 40));

        bproses.setBorder(null);
        bproses.setForeground(new java.awt.Color(255, 255, 255));
        bproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprosesActionPerformed(evt);
            }
        });
        getContentPane().add(bproses, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 600, 140, 30));

        Csupplier.setBorder(null);
        Csupplier.setForeground(new java.awt.Color(255, 255, 255));
        Csupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CsupplierActionPerformed(evt);
            }
        });
        getContentPane().add(Csupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, 30));

        tablebarangsementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Barang", "Nama barang", "Kategori", "Harga Jual", "Harga Beli", "Stok", "Deskripsi", "Satuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablebarangsementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebarangsementaraMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablebarangsementaraMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tablebarangsementara);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 540, 550));

        txthargasatuan.setBorder(null);
        txthargasatuan.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txthargasatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 105, 30));

        tablebarangfiks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_barang", "Nama Barang", "Harga Satuan", "Jumlah Barang", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablebarangfiks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablebarangfiksMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tablebarangfiks);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 550, 230));

        bhapus.setBorder(null);
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 360, 140, 40));

        tglpembelian.setBackground(new java.awt.Color(255, 255, 255));
        tglpembelian.setBorder(null);
        tglpembelian.setForeground(new java.awt.Color(255, 255, 255));
        tglpembelian.setOpaque(false);
        getContentPane().add(tglpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 340, 30));

        jLabel18.setText("Tanggal Transaksi Pembelian");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 166, -1));

        txtidbarang.setBorder(null);
        txtidbarang.setForeground(new java.awt.Color(255, 255, 255));
        txtidbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidbarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtidbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 100, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/revisi pembelian.png"))); // NOI18N
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabarangActionPerformed

    private void CsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CsupplierActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        String idbarang = txtidbarang.getText();
        String namabarang = txtnamabarang.getText();
        int hargasatuan = Integer.parseInt(txthargasatuan.getText());
        int jumlahbarang = Integer.parseInt(txtjumlahbarang.getText());
        
        int subtotal = hargasatuan*jumlahbarang;
        
        DefaultTableModel tbl= (DefaultTableModel) tablebarangfiks.getModel();
        tbl.addRow(new Object[]{
            String.valueOf (idbarang),
            namabarang,
            String.valueOf(hargasatuan),
            String.valueOf(jumlahbarang),
            String.valueOf(subtotal)
        });
        autosum();
    }//GEN-LAST:event_btambahActionPerformed

    private void tablebarangsementaraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebarangsementaraMouseReleased
        // TODO add your handling code here:
        int row = tablebarangsementara.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) tablebarangsementara.getModel();
        txtidbarang.setText(table.getValueAt(row, 0).toString());        
        txtnamabarang.setText(table.getValueAt(row, 1).toString());
        txthargasatuan.setText(table.getValueAt(row, 4).toString());
        
    }//GEN-LAST:event_tablebarangsementaraMouseReleased

    private void tablebarangsementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebarangsementaraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablebarangsementaraMouseClicked

    private void tablebarangfiksMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebarangfiksMouseReleased
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tablebarangfiksMouseReleased

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        String idbarang = txtidbarang.getText();                               
        String namabarang = txtnamabarang.getText();
        int hargasatuan = Integer.parseInt(txthargasatuan.getText());
        int jumlahbarang = Integer.parseInt(txtjumlahbarang.getText());
        int subtotal = hargasatuan*jumlahbarang;
        
        int row = tablebarangfiks.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) tablebarangfiks.getModel();
        table.removeRow(row);
        autosum();
    }//GEN-LAST:event_bhapusActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        String idbarang = txtidbarang.getText();
        String namabarang = txtnamabarang.getText();
        int hargasatuan = Integer.parseInt(txthargasatuan.getText());
        int jumlahbarang = Integer.parseInt(txtjumlahbarang.getText());
        int subtotal = hargasatuan*jumlahbarang;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        
    }//GEN-LAST:event_txtkembalianActionPerformed

    private void txtuangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangKeyReleased

    }//GEN-LAST:event_txtuangKeyReleased

    private void txtkembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkembalianKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianKeyPressed

    private void txtkembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkembalianKeyReleased

    }//GEN-LAST:event_txtkembalianKeyReleased

    private void txtuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuangActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuangActionPerformed

    private void bprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprosesActionPerformed
        String uangpembayaran = txtuang.getText();
        String total = txttotal.getText();
        String uangkembalian = txtkembalian.getText();
        String tgltransaksi = tglpembelian.getDateStringOrEmptyString();
        if (tgltransaksi.equals("")) {
            JOptionPane.showMessageDialog(null, "Tanggal tidak boleh kosong");
            return;
        }
        LocalDate currentDate = LocalDate.now();
        String id_supplier = Csupplier.getSelectedItem().toString().split(". ")[0];

        Koneksi cn = new Koneksi();
        try {
           Statement statement = koneksi.GetConnection().createStatement();
           statement.executeUpdate("insert into pembelian(id_supplier,total,uang,kembalian,tanggal_transaksi) "
                   + "VALUES ('"+id_supplier+"','"+total+"','"+uangpembayaran+"','"+uangkembalian+"','"+tgltransaksi+"')", Statement.RETURN_GENERATED_KEYS); 
           ResultSet generatedKey = statement.getGeneratedKeys();
            if (generatedKey.next()) {
                String idpembelian = generatedKey.getString(1);
                for (int i = 0; i <tablebarangfiks.getRowCount(); i++){
                    String idbarang = tablebarangfiks.getValueAt(i,0).toString();
                    int jumlahbarang = Integer.valueOf(tablebarangfiks.getValueAt(i,3).toString());
                    String subtotal = tablebarangfiks.getValueAt(i,4).toString();
                    statement.executeUpdate("insert into detail_pembelian(id_pembelian, id_barang,jumlah_barang,sub_total,created_at) "
                        + "VALUES ('"+idpembelian+"','"+idbarang+"','"+jumlahbarang+"','"+subtotal+"','"+currentDate+"')");
                    statement.executeUpdate("update barang set jumlah_stok = jumlah_stok + "+jumlahbarang+" where id_barang = '"+idbarang+"'");
                }
            }
            JOptionPane.showMessageDialog(null, "Pembelian berhasil");
            reset();
            datatable("");
        } catch(Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bprosesActionPerformed

    private void txtuangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangKeyTyped
 
    // TODO add your handling code here:
    }//GEN-LAST:event_txtuangKeyTyped

    private void txtkembalianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkembalianKeyTyped

    }//GEN-LAST:event_txtkembalianKeyTyped

    private void txtidbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidbarangActionPerformed

    private void txtuangInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtuangInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuangInputMethodTextChanged

    private void txtuangCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtuangCaretUpdate
        // TODO add your handling code here:
        int uangpembayaran = Integer.valueOf(txtuang.getText());
        int total = Integer.valueOf(txttotal.getText());
        int uangkembalian = uangpembayaran - total;
        txtkembalian.setText(String.valueOf(uangkembalian)); 
    }//GEN-LAST:event_txtuangCaretUpdate

    private void txtjumlahbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahbarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Csupplier;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bproses;
    private javax.swing.JButton btambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablebarangfiks;
    private javax.swing.JTable tablebarangsementara;
    private com.github.lgooddatepicker.components.DatePicker tglpembelian;
    private javax.swing.JTextField txthargasatuan;
    private javax.swing.JTextField txtidbarang;
    private javax.swing.JTextField txtjumlahbarang;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtuang;
    // End of variables declaration//GEN-END:variables
}
