        /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myTech;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Alfin Eka P
 */
public class Home extends javax.swing.JFrame {
    static private admin.UserAdmin userAdmin;
    /**
     * Creates new form Button
     */
    public Home(admin.UserAdmin userAdmin) {
        initComponents();
        if (userAdmin != null) {
            this.userAdmin = userAdmin;
            System.out.println(this.userAdmin.getId());
            System.out.println(this.userAdmin.getName());
            System.out.println(this.userAdmin.getUsername());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        bdatamaster = new javax.swing.JButton();
        btransaksi = new javax.swing.JButton();
        blaporan = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/Home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        bdatamaster.setForeground(new java.awt.Color(255, 255, 255));
        bdatamaster.setBorder(null);
        bdatamaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatamasterActionPerformed(evt);
            }
        });
        getContentPane().add(bdatamaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 140, -1));

        btransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btransaksi.setBorder(null);
        btransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 110, -1));

        blaporan.setForeground(new java.awt.Color(255, 255, 255));
        blaporan.setBorder(null);
        blaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blaporanActionPerformed(evt);
            }
        });
        getContentPane().add(blaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 33, 100, 40));

        bkeluar.setForeground(new java.awt.Color(255, 255, 255));
        bkeluar.setBorder(null);
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 633, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdatamasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatamasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdatamasterActionPerformed

    private void btransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btransaksiActionPerformed

    private void blaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blaporanActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (userAdmin == null) {
                    Login login = new Login();
                    login.setSize(450, 350);
                    login.setVisible(true);
                } else {
                    new Home(userAdmin).setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdatamaster;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton blaporan;
    private javax.swing.JButton btransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
