/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package myTech;
 
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class Kategori extends javax.swing.JInternalFrame {
    String sql;
    Statement stat;
    DefaultTableModel tableModel;
    Koneksi cn = new Koneksi();
    /**
     * Creates new form Kategori
     */
    public Kategori() {
        initComponents();
        tampil("");
    }

    void tampil (String query) {
        if (query.equals("")) {
            sql = "SELECT * FROM kategori";
        } else {
            sql = query;
        }
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Id Kategori");
        tableModel.addColumn("Nama Kategori");
        table.setModel(tableModel);
        try{
            stat = cn.GetConnection().createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()) {
                tableModel.addRow(new Object[]{
                    res.getString("id_kategori"),
                    res.getString("nama"),
                });
                table.setModel(tableModel);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }
    }
    
    void tambah () {
        try {
            stat = cn.GetConnection().createStatement();
            sql = "INSERT INTO kategori(nama) VALUES ('"+ txtkategori.getText() +"')";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            reset();
            tampil("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }
    }
    
    void reset(){
        txtkategori.setText("");
        txtidkategori.setText("");
    }
    
    void hapus () {
        try {
            stat = cn.GetConnection().createStatement();
            sql = "DELETE FROM kategori WHERE id_kategori = '"+ txtidkategori.getText() +"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            reset();
            tampil("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }
    }
    
    void cari() {
        sql = "SELECT * FROM kategori WHERE id_kategori LIKE '%"+ txtidkategori.getText() +"%' AND nama LIKE '%"+ txtkategori.getText() +"%'";
        tampil(sql);
    }
    
    void edit () {
        try {
            stat = cn.GetConnection().createStatement();
            sql = "UPDATE kategori SET nama = '"+ txtkategori.getText() +"' where id_kategori = '"+ txtidkategori.getText() +"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Update berhasil");
            reset();
            tampil("");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidkategori = new javax.swing.JTextField();
        txtkategori = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btambah = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bcari = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtidkategori.setEditable(false);
        txtidkategori.setBorder(null);
        getContentPane().add(txtidkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 380, -1));

        txtkategori.setBorder(null);
        getContentPane().add(txtkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 380, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("KATEGORI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1589, 20, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Kategori", "Nama Kategori"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 890, 240));

        btambah.setText("tambah");
        btambah.setBorder(null);
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        getContentPane().add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 100, 30));

        bedit.setText("edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 650, 55, -1));

        bcari.setText("cari");
        bcari.setBorder(null);
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 100, 30));

        bhapus.setText("hapus");
        bhapus.setBorder(null);
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 100, 30));

        bkeluar.setText("keluar");
        bkeluar.setBorder(null);
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 616, 100, 20));

        breset.setText("reset");
        breset.setBorder(null);
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        getContentPane().add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 550, 100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/kategori Fiks.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_bcariActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_btambahActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_beditActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetActionPerformed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        tableModel = (DefaultTableModel) table.getModel();
        txtidkategori.setText(tableModel.getValueAt(row, 0).toString());
        txtkategori.setText(tableModel.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tableMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton breset;
    private javax.swing.JButton btambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtidkategori;
    private javax.swing.JTextField txtkategori;
    // End of variables declaration//GEN-END:variables
}
