/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package myTech;
 
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class Kategori extends javax.swing.JFrame {
    String sql;
    Statement stat;
    DefaultTableModel tableModel;
    Koneksi cn = new Koneksi();
    /**
     * Creates new form Kategori
     */
    public Kategori() {
        initComponents();
        tampil("");
        txtidkategori.setBackground(new Color(0, 0, 0, 0));
        txtidkategori.setBorder(null);
        txtkategori.setBackground(new Color(0, 0, 0, 0));
        txtkategori.setBorder(null);
    }

    void tampil (String query) {
        if (query.equals("")) {
            sql = "SELECT * FROM kategori";
        } else {
            sql = query;
        }
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Id Kategori");
        tableModel.addColumn("Nama Kategori");
        table.setModel(tableModel);
        try{
            stat = cn.GetConnection().createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()) {
                tableModel.addRow(new Object[]{
                    res.getString("id_kategori"),
                    res.getString("nama"),
                });
                table.setModel(tableModel);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }
    }
    
    void tambah () {
        try {
            stat = cn.GetConnection().createStatement();
            sql = "INSERT INTO kategori(nama) VALUES ('"+ txtkategori.getText() +"')";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            reset();
            tampil("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }
    }
    
    void reset(){
        txtkategori.setText("");
        txtidkategori.setText("");
    }
    
    void hapus () {
        try {
            stat = cn.GetConnection().createStatement();
            sql = "DELETE FROM kategori WHERE id_kategori = '"+ txtidkategori.getText() +"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            reset();
            tampil("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }
    }
    
    void cari() {
        sql = "SELECT * FROM kategori WHERE id_kategori LIKE '%"+ txtidkategori.getText() +"%' AND nama LIKE '%"+ txtkategori.getText() +"%'";
        tampil(sql);
    }
    
    void edit () {
        try {
            stat = cn.GetConnection().createStatement();
            sql = "UPDATE kategori SET nama = '"+ txtkategori.getText() +"' where id_kategori = '"+ txtidkategori.getText() +"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Update berhasil");
            reset();
            tampil("");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadmin = new javax.swing.JLabel();
        csupplier = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtidkategori = new javax.swing.JTextField();
        txtkategori = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bedit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadminMouseClicked(evt);
            }
        });
        getContentPane().add(cadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 110, 20));

        csupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        csupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csupplierMouseClicked(evt);
            }
        });
        getContentPane().add(csupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 120, 20));

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 110, 20));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 110, 20));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 530, 110, 20));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 110, 20));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 100, 20));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 580, 120, 30));

        txtidkategori.setEditable(false);
        getContentPane().add(txtidkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 380, 30));

        txtkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkategoriActionPerformed(evt);
            }
        });
        getContentPane().add(txtkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 380, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("KATEGORI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 4, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Kategori", "Nama Kategori"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 870, 211));

        bedit.setBackground(new java.awt.Color(0, 102, 102));
        bedit.setForeground(new java.awt.Color(255, 255, 255));
        bedit.setText("EDIT");
        bedit.setBorder(null);
        bedit.setBorderPainted(false);
        bedit.setFocusPainted(false);
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 110, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_component_asset/Kategori.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_beditActionPerformed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        tableModel = (DefaultTableModel) table.getModel();
        txtidkategori.setText(tableModel.getValueAt(row, 0).toString());
        txtkategori.setText(tableModel.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tableMouseReleased

    private void txtkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkategoriActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        cari();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        reset();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Home home = new Home();
        home.setVisible(true);
        home.setExtendedState(Home.MAXIMIZED_BOTH);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void cadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadminMouseClicked
        // TODO add your handling code here:
        Admin a = new Admin();
        a.setVisible(true);
        dispose();
        a.setExtendedState(Admin.MAXIMIZED_BOTH);
    }//GEN-LAST:event_cadminMouseClicked

    private void csupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csupplierMouseClicked
        // TODO add your handling code here:
        Supplier a = new Supplier();
        a.setVisible(true);
        dispose();
        a.setExtendedState(Supplier.MAXIMIZED_BOTH);
    }//GEN-LAST:event_csupplierMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Barang a = new Barang();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (admin.UserAdmin.getName() == null) {
                    Login login = new Login();
                    login.setVisible(true);
                    login.setExtendedState(Login.MAXIMIZED_BOTH);
                } else {
                    new Kategori().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedit;
    private javax.swing.JLabel cadmin;
    private javax.swing.JLabel csupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtidkategori;
    private javax.swing.JTextField txtkategori;
    // End of variables declaration//GEN-END:variables
}
